services:
  - type: web
    name: tasktracker-backend
    runtime: node
    buildCommand: chmod +x ./build.sh && ./build.sh
    startCommand: cd backend && npm start
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: GITHUB_WEBHOOK_SECRET
        value: ${GITHUB_WEBHOOK_SECRET}
      - key: SUPABASE_URL
        value: ${SUPABASE_URL}
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}
      - key: DATABASE_URL
        value: ${DATABASE_URL}
